---
title: "Analog Gauge Reader"
author: "Devesh"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analog Gauge Detection through Camera

Problem Statement:
To extract readings from  a picture of an analog circular gauge.

Approach 1:
Idea:
To use computer vision to detect pointing needle and it’s angle and return the values according to the gauge calibration parameters. The image is clicked through a phone through an AR app to provide overlays for to click the image best for the image processing algorithm
Steps:


Using an OpenCV function HoughCircles, we find out the circle all circular constructs found in that image
We set a range of radii to detect from and average them out and set the resulting circle (radius, centre coordinates) are the dial gauge
We then detect the lines using an OpenCV function gough lines 
The lines used for the detecting the needle need to have a set difference from the centre of circle, the most distant point and nearest point are set as a fraction of the radius
We then choose the first line from a list of final lines as the approximation of the line of the needle
Reading the QR code from below the images, the app sends in the gauge number to the firebase database 
The trigger variable when the image is put into the database is set to ‘False’
From there we download the image and gauge number from the database
A csv file read the number and puts out the gauge calibration details like the minimum angle, maximum angle of the needle and it’s corresponding values.
After getting the values we update the trigger to true and also update the value of the reading
Advantages:
No need of collecting images for the algorithm to work
Disadvantages:
The images have to clicked in a very specific manner or the algorithm will not work
Feature extraction is manual 



Approach 2:
Idea:
Using machine learning and image processing to detect and read the values from analog gauge
Steps:
Multiples images are captured keeping the camera at a fixed location
Using OpenCV dataset is generated by separating needle and dial
Needle images and dial images are separated out
Needle is rotated in various angles and is overlaid on the dial image to generate a synthetic dataset. The angles/rotation step in fixed
More image processing like scaling and perspective transform are done
Noise is artificially added to make the classifier more robust
Deep learning classification
There are 30 classes to predict each indicating the 30 steps of range of values of the dial
Ensemble CNN is used for prediction

Advantages:
No need to setup manual calibration parameters
Disadvantages:
Need to have separate needle and dial images beforehand
Will only work on one type of dial
Camera needs to be fixed

